robogui/robo/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path(
        "resultsperdiscipline/<int:pk>",
        views.ResultsPerDisciplineView.as_view(),
        name="results-per-discipline",
    ),
    path(
        "resultsperdiscipline/<int:pk>/<str:wertung>/",
        views.ResultsPerDisciplineView.as_view(),
        name="results-per-discipline",
    ),
    path("athletes/", views.AthletesListView.as_view(), name="athletes-list"),
    path(
        "athletes/<int:pk>",
        views.AthletesListPerClubView.as_view(),
        name="athletes-list",
    ),
    path(
        "athlete/add/<int:pk>", views.AthleteCreateView.as_view(), name="athlete-create"
    ),
    path("athlete/<int:pk>/", views.AthleteUpdateView.as_view(), name="athlete-update"),
    path(
        "athlete/<int:pk>/delete/",
        views.AthleteDeleteView.as_view(),
        name="athlete-delete",
    ),
    path("teams/", views.TeamsView.as_view(), name="teams"),
    path("teams/<str:wertung>/", views.TeamsView.as_view(), name="teams"),
    path("team/add/", views.TeamCreateView.as_view(), name="team-add"),
    path("team/<int:pk>", views.TeamUpdateView.as_view(), name="team-update"),
    path("team/<int:pk>/delete/", views.TeamDeleteView.as_view(), name="team-delete"),
    path("out/<str:outputtype>/", views.csv_view, name="out"),
    path("competition/", views.CompetitionListView.as_view(), name="competition-list"),
    path(
        "competition/add/",
        views.CompetitionCreateView.as_view(),
        name="competition-add",
    ),
    path(
        "competition/<int:pk>/",
        views.CompetitionUpdateView.as_view(),
        name="competition-update",
    ),
    path(
        "competition/<int:pk>/delete",
        views.CompetitionDeleteView.as_view(),
        name="competition-delete",
    ),
    path("disciplines/", views.DisciplineListView.as_view(), name="disciplines-list"),
    path(
        "discipline/add/", views.DisciplineCreateView.as_view(), name="discipline-add"
    ),
    path(
        "discipline/<int:pk>/",
        views.DisciplineUpdateView.as_view(),
        name="discipline-update",
    ),
    path(
        "discipline/<int:pk>/delete/",
        views.DisciplineDeleteView.as_view(),
        name="discipline-delete",
    ),
]

robogui/robogui/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("robo/", include("robo.urls")),
    path("admin/", admin.site.urls),
]

robogui/robo/models.py
import datetime
import re

from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.fields import validators
from django.urls import reverse

from robinsoncup import teams
from robinsoncup.io_base import REGEX_TIME


class ModelCompetition(models.Model):
    name = models.CharField(max_length=300)
    date = models.DateField(help_text="2022-12-24")
    location = models.CharField(max_length=200)
    points_per = models.IntegerField(
        choices=[(p.value, p.name) for p in teams.PointsPer],
        default=teams.PointsPer.Altersklasse,
    )

    def __str__(self):
        return f"{self.name}, {self.date} ({self.location})"

    def get_absolute_url(self):
        return reverse("competition-update", kwargs={"pk": self.pk})


class ModelDiscipline(models.Model):
    name = models.CharField(max_length=100, blank=True, unique=True)
    smaller_is_better = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.name}, {self.smaller_is_better}"

    def get_absolute_url(self):
        return reverse("disciplines-list")


class ModelTeam(models.Model):
    name = models.CharField(max_length=50)
    verein = models.CharField(max_length=100)
    startnumber = models.PositiveIntegerField(null=True)

    def get_startnumber(self) -> str:
        if self.startnumber is None:
            return ""
        return str(self.startnumber)

    def get_absolute_url(self):
        return reverse("team-update", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.name} ({self.verein}), Startnummer {self.startnumber}"
    
    class Meta:
        unique_together = ("name", "verein")


class ModelAthlete(models.Model):
    name = models.CharField(max_length=100)
    yob = models.PositiveIntegerField(
        validators=[
            validators.MinValueValidator(1900),
            validators.MaxValueValidator(datetime.datetime.now().year),
        ],
    )
    # to being able to delete teams (while keeping the athletes): nullable, emptyable
    team = models.ForeignKey("ModelTeam", on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.name} ({self.yob})"

    def get_absolute_url(self):
        return reverse("teams")
    
    class Meta:
        unique_together = ("name", "yob")


class ModelResult(models.Model):
    discipline = models.ForeignKey("ModelDiscipline", on_delete=models.CASCADE)
    team = models.ForeignKey("ModelTeam", on_delete=models.CASCADE)
    result = models.CharField(max_length=100, blank=True)

    def __str__(self):
        return f"{self.result} ({self.discipline}, {self.team})"

    def clean(self):
        # cleaned_data = super().clean()
        # if cleaned_data:
        if self.result == "":
            return
        if self.discipline.smaller_is_better:
            if not re.search(REGEX_TIME, self.result):
                msg = f"Result {self.result} is not valid (regex: {REGEX_TIME})"
                raise ValidationError(msg)
        else:
            try:
                float(self.result.replace(",", ".").strip())
            except ValueError:
                msg = f"Result {self.result} is not valid (no time)"
                raise ValidationError(msg)

robogui/robo/forms.py
from django.forms import ModelForm
from django.forms import widgets

from . import models


class CompetitionForm(ModelForm):
    class Meta:
        model = models.ModelCompetition
        fields = "__all__"


class TeamForm(ModelForm):
    class Meta:
        model = models.ModelTeam
        fields = "__all__"

robogui/robo/views.py
import logging
import os.path
from collections import namedtuple
from datetime import date

import numpy as np
from django.forms import modelformset_factory
from django.http import Http404
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from robinsoncup import argparse_functions
from robinsoncup.teams import WERTUNGEN
from . import models
from . import csv_output

LOGGER = logging.getLogger(__name__)

NUMBER_OF_DISCIPLINES = 5
MAX_ATHLETES_PER_TEAM = 5

OUT_FILES = {
    "csv": "../0_input_auto-generated-from-robogui.csv",
    "startlist": "../1_startlist_auto-generated-from-robogui.pdf",
    "points": "../2_points_auto-generated-from-robogui.csv",
    "results": "../3_results_auto-generated-from-robogui.pdf",
    "certificates": "../4_certificates_auto-generated-from-robogui.pdf",
}

TEXT_ONLY_CERTIFICATES = True


def index(request):
    return render(request, "robo/index.html", {})


def csv_view(request, outputtype):
    allowed_outputtypes = ("csv", "startlist", "results")
    if outputtype not in allowed_outputtypes:
        return render(
            request,
            "robo/index.html",
            {
                "status_message": f"Request str not allowed. Allowed: {allowed_outputtypes}",
            },
        )

    status_message = None
    if outputtype == "csv":
        try:
            csv_output.data_to_csv(OUT_FILES["csv"])
            ArgParseArgs = namedtuple("ArgParseArgs", ["input", "output", "verbose"])
            to_points_args = ArgParseArgs(OUT_FILES["csv"], OUT_FILES["points"], False)
            argparse_functions.to_points(to_points_args)
        except Exception as e:
            status_message = f"Error: {str(e)}"
        else:
            LOGGER.info(f"Output written to {OUT_FILES['csv']}")
            LOGGER.info(f"Output written to {OUT_FILES['points']}")
            status_message = (
                f"2 files created: {OUT_FILES['csv']}, {OUT_FILES['points']}"
            )
    elif outputtype == "startlist":
        if not os.path.exists(OUT_FILES["csv"]):
            status_message = (
                f"Input file '{OUT_FILES['csv']}' does not exist -> create CSV first"
            )
        else:
            ArgParseArgs = namedtuple(
                "ArgParseArgs", ["input", "output", "no_open", "verbose"]
            )
            response = HttpResponse(
                content_type="application/pdf",
                headers={"Content-Disposition": 'attachment; filename="startlist.pdf"'},
            )
            try:
                to_startlist_args = ArgParseArgs(
                    OUT_FILES["csv"], OUT_FILES["startlist"], True, False
                )
                to_startlist_args_response = ArgParseArgs(
                    OUT_FILES["csv"], response, True, False
                )
            except Exception as e:
                status_message = f"Error: {str(e)}"
            else:
                argparse_functions.to_startlist(to_startlist_args)
                argparse_functions.to_startlist(to_startlist_args_response)
                return response
    elif outputtype == "results":
        if not os.path.exists(OUT_FILES["points"]):
            status_message = (
                f"Input file '{OUT_FILES['points']}' does not exist -> create csv first"
            )
        else:
            ArgParseArgs = namedtuple(
                "ArgParseArgs",
                [
                    "input",
                    "output",
                    "certificates_output",
                    "no_open",
                    "skip_certificates",
                    "verbose",
                    "text_only_certificates",
                ],
            )
            try:
                to_results_args = ArgParseArgs(
                    OUT_FILES["points"],
                    OUT_FILES["results"],
                    OUT_FILES["certificates"],
                    True,
                    False,
                    False,
                    TEXT_ONLY_CERTIFICATES,
                )
                argparse_functions.to_results(to_results_args)
            except Exception as e:
                status_message = f"Error: {str(e)}"
            else:
                status_message = f"Results, certificates created: {OUT_FILES['results']}, {OUT_FILES['certificates']}"

    return render(
        request,
        "robo/index.html",
        {
            "status_message": status_message,
        },
    )


def get_teams_of_wertung(teams, wertung: str) -> list:
    cur_year = date.today().year
    age_max, age_min = WERTUNGEN[wertung]
    teams_cur_wertung = []
    for t in teams:
        athletes_cur_team = models.ModelAthlete.objects.filter(team__id=t.id)
        mean_yob = np.mean([a.yob for a in athletes_cur_team])
        if (cur_year - age_max) <= mean_yob <= (cur_year - age_min):
            teams_cur_wertung.append(t)
    return teams_cur_wertung


class AthletesListView(generic.ListView):
    model = models.ModelAthlete
    context_object_name = "athletes"


class AthletesListPerClubView(AthletesListView):
    template_name = "robo/modelathleteperclub_list.html"

    def get_queryset(self):
        team_id = self.kwargs.get("pk")
        return models.ModelAthlete.objects.filter(team__id=team_id)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            team_name = models.ModelTeam.objects.get(id=self.kwargs["pk"]).name
        except models.ModelTeam.DoesNotExist:
            team_name = ""
        context.update({"team_name": team_name})
        return context


class AthleteCreateView(generic.CreateView):
    model = models.ModelAthlete
    fields = ["name", "yob"]
    template_name = "robo/create_form.html"

    def form_valid(self, form):
        team_id = self.kwargs.get("pk")
        form.instance.team = models.ModelTeam.objects.get(id=team_id)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("athletes-list", kwargs={"pk": self.kwargs["pk"]})


class AthleteUpdateView(generic.UpdateView):
    model = models.ModelAthlete
    fields = ["name", "yob", "team"]
    template_name = "robo/update_form.html"


class AthleteDeleteView(generic.DeleteView):
    model = models.ModelAthlete
    success_url = reverse_lazy("athletes-list")
    template_name = "robo/confirm_delete.html"


class TeamsView(generic.ListView):
    def get(self, request, *args, **kwargs):
        wertung = kwargs.get("wertung")
        if wertung is not None and wertung not in WERTUNGEN:
            raise Http404(f"Wertung {wertung} does not exist")
        teams = models.ModelTeam.objects.order_by("pk")
        number_teams_per_wertung = {
            w: len(get_teams_of_wertung(teams, w)) for w in reversed(WERTUNGEN.keys())
        }
        if wertung:
            teams_cur_wertung = get_teams_of_wertung(teams, wertung)
        else:
            teams_cur_wertung = list(teams)
        context = {
            "teams": teams_cur_wertung,
            "wertungen": number_teams_per_wertung,
            "n_total_teams": len(teams),
        }
        return render(
            request,
            "robo/teams.html",
            context,
        )


class ResultsPerDisciplineView(generic.UpdateView):
    def get(self, request, *args, **kwargs):
        discipline_id = kwargs.get("pk")
        discipline = models.ModelDiscipline.objects.get(pk=discipline_id)

        teams = models.ModelTeam.objects.order_by("pk")
        if kwargs.get("wertung"):
            teams = get_teams_of_wertung(teams, kwargs.get("wertung"))
        for t in teams:
            models.ModelResult.objects.get_or_create(
                team=t, discipline=discipline, defaults={"result": ""}
            )

        results_formset = modelformset_factory(
            models.ModelResult, fields=["team", "result"], max_num=len(teams)
        )
        results = models.ModelResult.objects.filter(
            discipline=discipline, team_id__in=[t.id for t in teams]
        ).order_by("team__id")
        results_form = results_formset(queryset=results)
        for form in results_form.forms:
            form.fields["team"].disabled = True
        return render(
            request,
            "robo/resultsperdiscipline.html",
            {
                "number_of_teams": len(teams),
                "results_form": results_form,
                "discipline": discipline,
                "wertungen": list(reversed(WERTUNGEN.keys())),
            },
        )

    def post(self, request, *args, **kwargs):
        discipline = models.ModelDiscipline.objects.get(pk=kwargs.get("pk"))
        teams = models.ModelTeam.objects.order_by("pk")
        if kwargs.get("wertung"):
            teams = get_teams_of_wertung(teams, kwargs.get("wertung"))
        results_formset = modelformset_factory(models.ModelResult, fields=["result"])
        results = models.ModelResult.objects.filter(
            discipline=discipline, team_id__in=[t.id for t in teams]
        ).order_by("team__id")
        results_form = results_formset(request.POST, queryset=results)
        n_results_updated = 0
        if results_form.is_valid():
            for res in results_form.cleaned_data:
                if res["id"] is None:
                    # this happens if no get request was sent before (only post request eg via unittests)
                    # current workaround: there must be results (objects) available and res["id"] must be that object,
                    # this means that form-?-id must be the id of the respective results object
                    raise NotImplementedError
                assert isinstance(res["id"], models.ModelResult)
                if res["id"].result != res["result"]:
                    res["id"].result = res["result"]
                    res["id"].save()

robogui/robo/templates/robo/confirm_delete.html
{% extends "base.html" %}

{% block title %}confirm{% endblock %}

{% block content %}

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Yes, delete">
</form>

{% endblock %}

robogui/robo/templates/robo/create_form.html
{% extends "base.html" %}
{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Create">
</form>

{% endblock %}

robogui/robo/templates/robo/disciplines.html
{% extends "base.html" %}

{% block title %}Disciplines{% endblock %}

{% block content %}

<form action="{% url 'disciplines-detail' %}" method="post">
    {% csrf_token %}
    {{ management_form }}
    <table>
        {% for form, disc_id in formset_w_ids %}
        <tr>
            {{ form }}
            {% if disc_id %}
                <td><a href="{% url 'results-per-discipline' disc_id %}">Add results</a></td>
            {% endif %}
        </tr>
        {% endfor %}
    </table>
    <input type="submit" value="Save">
</form>

{% endblock %}

robogui/robo/templates/robo/index.html
{% extends "base.html" %}

{% block title %}Index{% endblock %}

{% block content %}

<h2>Robinsoncup - Startseite</h2>

{% endblock %}

robogui/robo/templates/robo/modelathlete_list.html
{% extends "base.html" %}

{% block title %}athletes{% endblock %}

{% block content %}

{% if team_name %}
<h2>Athletes of {{team_name}}</h2>
{% else %}
<h2>Athletes</h2>
{% endif %}

{% if athletes %}
    <ul>
    {% for a in athletes %}
        <li><a href="{% url 'athlete-update' a.id %}">{{ a.name }}</a>
            ({{a.yob}}, {% if a.team %} <a href="{% url 'team-update' a.team.id %}">{{ a.team.name }}</a>{% else %} No team{% endif %})
            <a href="{% url 'athlete-delete' a.id %}">Delete</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No athletes available</p>
{% endif %}

{% block add_athlete_button %}
{% endblock %}

{% endblock %}

robogui/robo/templates/robo/modelathleteperclub_list.html
{% extends "robo/modelathlete_list.html" %}


{% block add_athlete_button %}
<a href="{% url 'athlete-create' view.kwargs.pk %}">Add athlete to {{team_name}}</a>
{% endblock %}

robogui/robo/templates/robo/modelcompetition_list.html
{% extends "base.html" %}

{% block content %}
    <h2>Competition</h2>
    <ul>
        {% if competition %}
            {% for c in competition %}
            <li><a href="{% url 'competition-update' c.id %}">{{ c.name }}</a> ({{ c.date }})
                <a href="{% url 'competition-delete' c.id %}">Delete</a>
            </li>
            {% endfor %}
        {% else %}
            <a href="{% url 'competition-add' %}">Add new competition</a>
        {% endif %}
    </ul>
{% endblock %}

robogui/robo/templates/robo/modeldiscipline_list.html
{% extends "base.html" %}

{% block content %}
    <h2>Disciplines</h2>
    <ul>
        {% for d in disciplines %}
            <li><a href="{% url 'discipline-update' d.id %}">{{ d.name }}</a>, Smaller is better: {{ d.smaller_is_better }}
                <a href="{% url 'discipline-delete' d.id %}">Delete</a>
                <a href="{% url 'results-per-discipline' d.id %}">Results</a>
            </li>
        {% endfor %}
    </ul>
<a href="{% url 'discipline-add' %}">Add new discipline</a>
{% endblock %}

robogui/robo/templates/robo/resultsperdiscipline.html
{% extends "base.html" %}

{% block title %}results{% endblock %}

{% block content %}

<a href="{% url 'results-per-discipline' discipline.id %}">ALL</a>
{% for w in wertungen %}
<a href="{% url 'results-per-discipline' discipline.id w %}">{{w}}</a>
{% endfor %}
{% if number_of_teams %}
<h2>Results for {{discipline.name}}</h2>
<form action="{% url 'results-per-discipline' discipline.id %}" method="post">
    {% csrf_token %}
    {{ results_form }}
    <input type="submit" value="Update">
</form>
{% else %}
<p>No teams available</p>
{% endif %}

{% endblock %}

robogui/robo/templates/robo/teams.html
{% extends "base.html" %}

{% block title %}Teams{% endblock %}

{% block content %}

<h2>Teams</h2>
<a href="{% url 'teams' %}">ALL ({{n_total_teams}})</a>
{% for w, number_teams in wertungen.items %}
    <a href="{% url 'teams' w %}">{{w}} ({{number_teams}})</a>
{% endfor %}
{% if teams %}
    <ul>
    {% for t in teams %}
        <li><a href="{% url 'team-update' t.id %}">{{ t.name }}</a> ({{t.verein}})
            <a href="{% url 'team-delete' t.id %}">Delete</a>
            <a href="{% url 'athletes-list' t.id %}">Athletes ({{t.modelathlete_set.count}})</a>
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No teams available</p>
{% endif %}
<a href="{% url 'team-add' %}">New team</a>

{% endblock %}

robogui/robo/templates/robo/update_form.html
{% extends "base.html" %}
{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Update">
</form>

{% endblock %}